export const TOKENS = {
  SPEECH_TO_TEXT: Symbol('SPEECH_TO_TEXT'),
  LANGUAGE_MODEL: Symbol('LANGUAGE_MODEL'),
  TEXT_TO_SPEECH: Symbol('TEXT_TO_SPEECH'),
  EMBEDDINGS: Symbol('EMBEDDINGS'),
  EVALUATION_MODEL: Symbol('EVALUATION_MODEL'),
  RETRIEVAL: Symbol('RETRIEVAL'),
  VECTOR_STORE: Symbol('VECTOR_STORE'),
  EVENT_BUS: Symbol('EVENT_BUS'),
  CALL_SESSION_STORE: Symbol('CALL_SESSION_STORE'),
  JOB_QUEUE: Symbol('JOB_QUEUE'),
} as const;
