import { useMemo, useState } from 'react';
import type { ActiveSession, TrainingGroup } from '../../domain/entities';
import { calculateRisk } from '../../application/services/risk-radar';
import { difficultyLabels, emotionLabels, formatDuration } from '../../domain/value-objects';
import { EmptyState, StatusBadge } from '../components/common';

export function ActivePage({ sessions, groups, onObserve }: { sessions: ActiveSession[]; groups: TrainingGroup[]; onObserve: (id: string) => void }) {
  const [query, setQuery] = useState(''); const [group, setGroup] = useState(''); const [scenario, setScenario] = useState(''); const [status, setStatus] = useState('');
  const visible = useMemo(() => [...sessions].filter((item) => (!query || `${item.student.name} ${item.scenarioTitle}`.toLowerCase().includes(query.toLowerCase())) && (!group || item.student.groupId === group) && (!scenario || item.scenarioId === scenario) && (!status || item.status === status)).sort((a, b) => calculateRisk(b.riskSignals).score - calculateRisk(a.riskSignals).score), [sessions, query, group, scenario, status]);
  return <div className="td-page"><header className="td-page-head"><div><p className="td-kicker">Мониторинг</p><h2>Активные занятия</h2></div><StatusBadge tone="good">{sessions.length} на линии</StatusBadge></header>
    <section className="td-filters" aria-label="Фильтры активных занятий"><label>Поиск<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Имя или сценарий" /></label><label>Группа<select value={group} onChange={(event) => setGroup(event.target.value)}><option value="">Все</option>{groups.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Сценарий<select value={scenario} onChange={(event) => setScenario(event.target.value)}><option value="">Все</option>{[...new Map(sessions.map((item) => [item.scenarioId, item])).values()].map((item) => <option key={item.scenarioId} value={item.scenarioId}>{item.scenarioTitle}</option>)}</select></label><label>Статус<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Все</option><option value="live">В разговоре</option><option value="paused">Пауза</option><option value="finishing">Завершение</option></select></label></section>
    {visible.length === 0 ? <EmptyState>По выбранным фильтрам сессий нет.</EmptyState> : <div className="td-table-wrap"><table className="td-table"><thead><tr><th>Обучающийся</th><th>Сценарий</th><th>Режим</th><th>Время</th><th>Карточка</th><th>Состояние</th><th>Риск ↓</th><th /></tr></thead><tbody>{visible.map((item) => { const risk = calculateRisk(item.riskSignals); return <tr key={item.callId}><td><strong>{item.student.name}</strong><small>{groups.find((entry) => entry.id === item.student.groupId)?.name}</small></td><td><strong>{item.scenarioTitle}</strong><small>{difficultyLabels[item.difficulty]}</small></td><td><StatusBadge tone={item.mode === 'exam' ? 'warning' : 'neutral'}>{item.mode === 'exam' ? 'Экзамен' : 'Тренировка'}</StatusBadge></td><td>{formatDuration(item.durationSec)}</td><td><div className="td-progress"><i style={{ width: `${item.cardProgress}%` }} /></div><small>{item.cardProgress}%</small></td><td>{emotionLabels[item.emotionalState.primary]}</td><td><StatusBadge tone={risk.level === 'high' ? 'danger' : risk.level === 'medium' ? 'warning' : 'good'}>{risk.score}</StatusBadge></td><td><button className="td-btn td-btn--secondary" onClick={() => onObserve(item.callId)}>Наблюдать</button></td></tr>; })}</tbody></table></div>}
  </div>;
}
